import {useEffect,useState} from 'react';

type Candidate={key:string;name:string;home_team:string;home_team_first:boolean};
type Conflict={id:number;reason:string;employee:string;team:string;start:string;end:string;candidates:Candidate[]};
type Result={remaining_conflicts:{id:number;reason:string}[];[key:string]:unknown};
type Props={week:string;teamName:(key:string)=>string;displayTime:(value:string)=>string;onClose:()=>void;onUpdated:(state:Result)=>void};
export default function ConflictResolver({week,teamName,displayTime,onClose,onUpdated}:Props){
 const [items,setItems]=useState<Conflict[]>([]);const [skipped,setSkipped]=useState<number[]>([]);
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [loaded,setLoaded]=useState(false);
 async function load(){try{const r=await fetch('/api/conflicts?week='+encodeURIComponent(week));const data=await r.json();if(!r.ok)throw Error(data.error||'Could not load conflicts');setItems(data.conflicts);setLoaded(true)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load()},[week]);
 const item=items.find(x=>!skipped.includes(x.id));
 async function assign(key:string){if(!item)return;setBusy(true);setError('');try{const r=await fetch('/api/resolve-conflict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({week,shift_id:item.id,employee:key})});const data=await r.json();if(!r.ok)throw Error(data.error||'Replacement is no longer eligible');onUpdated(data);await load()}catch(e){setError((e as Error).message);await load()}finally{setBusy(false)}}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="modal conflict-modal" role="dialog" aria-modal="true" aria-label="Resolve schedule conflicts"><div className="modal-head"><h2>Resolve conflicts</h2><button onClick={onClose} aria-label="Close">×</button></div>{error&&<p className="copy-error" role="alert">{error}</p>}{!loaded?<p>Checking the draft…</p>:!item?<div><p>{items.length?`${items.length} conflict(s) remain after skipped items. You can edit those shifts manually or return later.`:'No publish-blocking shift conflicts remain.'}</p><button className="primary" onClick={onClose}>Done</button></div>:<><p className="form-hint">{items.filter(x=>!skipped.includes(x.id)).length} to review · {items.length} total</p><div className="conflict-summary"><strong>{item.employee} · {teamName(item.team)}</strong><div>{displayTime(item.start)} → {displayTime(item.end)}</div><p>{item.reason}</p></div><h3>Eligible replacements</h3>{item.candidates.length?<div className="conflict-candidates">{item.candidates.map(c=><button key={c.key} className="team-directory-row" disabled={busy} onClick={()=>assign(c.key)}><span className="person-avatar">{c.name[0]}</span><span className="team-directory-copy"><strong>{c.name}</strong><small>{teamName(c.home_team)} · {c.home_team_first?'Home team':'Cross-team'}</small></span><span className="team-edit">Assign →</span></button>)}</div>:<p>No eligible replacement meets the current qualifications, availability, and rest checks. Leave this shift for manual editing.</p>}<div className="modal-actions"><button className="quiet" onClick={onClose}>Close</button><button className="secondary" onClick={()=>setSkipped([...skipped,item.id])}>Skip this shift</button></div></>}</section></div>;
}
