import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CalendarDays, UsersRound, PhoneCall, Layers, Settings2, CircleHelp, RefreshCw, Send, Plus} from 'lucide-react';
import AvailabilityCalendar from './AvailabilityCalendar';
import ScheduleRecords from './ScheduleRecords';
import {labels, formatDateTime} from './locale';
import './style.css';

type Preference={shift_type?:string;day_night?:string;on_call_grouping?:string;weekend_continuity?:boolean;block_length?:number};
type Template={days:number[];start:number;end:number;mode:string;required:number;weight:number};
type Team={key:string;name:string;skill:string;coverage_template:Template[];preferences:Preference};
type Person={key:string;name:string;phone:string;team:string;classification:string;skills:string[];preferences:Preference;availability:{start:string;end:string}[];available_windows:{start:string;end:string}[]};
type Coverage={id:number;team:string;start:string;end:string;mode:string;required:number;skill:string;weight:number;covered:number;covered_minutes:number;total_minutes:number};
type Shift={id:number;employee:string;team:string;start:string;end:string;mode:string;published:boolean;cross_team:boolean;break_minutes:number;location:string;role:string;notes:string};
type State={week:string;batch:string;timezone:string;teams:Team[];employees:Person[];coverage:Coverage[];shifts:Shift[];advisories:{code:string;message:string}[];published_weeks:string[];revisions:{revision:number}[];absences:{id:number;employee:string;name:string;start:string;end:string;kind:string;note:string;affected:number[]}[];callouts:{id:number;shift:number|null;employee:string;start:string;end:string;note:string}[]};
type OnCall={people:{id:number;name:string;phone:string;team:string;start:string;end:string;current:boolean;mode:string}[];gaps:{team:string;start:string;end:string;missing:number}[]};
const TZ='America/Vancouver';
const pad=(n:number)=>String(n).padStart(2,'0');
function parts(value:string){const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));return Object.fromEntries(p.map(x=>[x.type,x.value]));}
function inputTime(value:string){const p=parts(value);return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
function displayTime(value:string){return formatDateTime(value,TZ);}
function dateKey(value:string){const p=parts(value);return `${p.year}-${p.month}-${p.day}`;}
function toInstant(local:string){const [d,t]=local.split('T');const [y,m,day]=d.split('-').map(Number);const [h,min]=t.split(':').map(Number);const desired=Date.UTC(y,m-1,day,h,min);let candidate=desired;for(let i=0;i<3;i++){const p=parts(new Date(candidate).toISOString());const actual=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute);candidate+=desired-actual;}return new Date(candidate).toISOString();}
function weekStart(){const d=new Date();const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return dateKey(d.toISOString());}
class ApiError extends Error{blocked_shifts:{id:number;reason:string}[];constructor(result:{error?:string;blocked_shifts?:{id:number;reason:string}[]}){super(result.error||'Request failed');this.blocked_shifts=result.blocked_shifts||[];}}
async function api<T>(path:string, payload?:object):Promise<T>{const response=await fetch('/api/'+path,{method:payload?'POST':'GET',headers:{'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined});const result=await response.json();if(!response.ok)throw new ApiError(result);return result;}
const defaultPreferences:Preference={shift_type:'either',day_night:'consistent',on_call_grouping:'paired',weekend_continuity:true,block_length:2};
function PrefFields({value,onChange}:{value:Preference;onChange:(v:Preference)=>void}){const set=(key:keyof Preference,v:string|boolean|number)=>onChange({...value,[key]:v});return <div className="form-grid"><label>Day or night<select value={value.shift_type||'either'} onChange={e=>set('shift_type',e.target.value)}><option value="either">Either</option><option value="days">Prefer days</option><option value="nights">Prefer nights</option></select></label><label>Shift consistency<select value={value.day_night||'consistent'} onChange={e=>set('day_night',e.target.value)}><option value="consistent">Keep day/night blocks</option><option value="rotation">Rotate day/night</option><option value="flexible">Flexible</option></select></label><label>On-call grouping<select value={value.on_call_grouping||'paired'} onChange={e=>set('on_call_grouping',e.target.value)}><option value="paired">Prefer paired periods</option><option value="isolated">Prefer isolated periods</option><option value="either">Either</option></select></label><label>Preferred block length<input type="number" min="1" max="14" value={value.block_length||2} onChange={e=>set('block_length',Number(e.target.value))}/></label><label className="check"><input type="checkbox" checked={value.weekend_continuity!==false} onChange={e=>set('weekend_continuity',e.target.checked)}/> Keep weekend times consistent</label></div>}

function App(){
 const [data,setData]=useState<State|null>(null);const [view,setView]=useState<'schedule'|'coverage'|'oncall'|'people'|'teams'|'help'>('schedule');
 const [team,setTeam]=useState(localStorage.getItem('selected-team')||'team-1');const [week,setWeek]=useState(weekStart());const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [oncall,setOncall]=useState<OnCall|null>(null);
 const [editing,setEditing]=useState<string|null>(null);const [form,setForm]=useState<Record<string,any>>({});
 const [blocked,setBlocked]=useState<Record<number,string>>({});
 const [calloutShift,setCalloutShift]=useState<Shift|null>(null);const [calloutStart,setCalloutStart]=useState('');const [calloutEnd,setCalloutEnd]=useState('');const [calloutNote,setCalloutNote]=useState('');
 const [teamSearch,setTeamSearch]=useState('');const [peopleSearch,setPeopleSearch]=useState('');
 const refresh=async(w=week)=>setData(await api<State>('state?week='+encodeURIComponent(w)));
 useEffect(()=>{setBlocked({});refresh().catch(e=>setMessage(e.message));},[week]);
 useEffect(()=>{if(data?.teams.length&&team!=='all'&&!data.teams.some(t=>t.key===team))setTeam(data.teams[0].key);},[data?.teams,team]);
 useEffect(()=>{localStorage.setItem('selected-team',team);if(view==='oncall')api<OnCall>('oncall?team='+encodeURIComponent(team)).then(setOncall).catch(e=>setMessage(e.message));},[team,view,data?.batch]);
 const people=useMemo(()=>new Map(data?.employees.map(p=>[p.key,p])||[]),[data]);
 const teamName=(key:string)=>data?.teams.find(t=>t.key===key)?.name||key;
 const coverage=data?.coverage.filter(x=>team==='all'||x.team===team)||[];const shifts=data?.shifts.filter(x=>team==='all'||x.team===team)||[];
 const matchingTeams=data?.teams.filter(t=>t.name.toLocaleLowerCase().includes(teamSearch.trim().toLocaleLowerCase()))||[];
 const personMatches=(p:Person)=>{const term=peopleSearch.trim().toLocaleLowerCase();return !term||[p.name,teamName(p.team),...p.skills].some(x=>x.toLocaleLowerCase().includes(term));};
 const days=Array.from({length:7},(_,i)=>{const d=new Date(week+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+i);return d.toISOString().slice(0,10)});
 const moveWeek=(offset:number)=>{const d=new Date(week+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset*7);setWeek(d.toISOString().slice(0,10));};
 async function act(path:string,payload:object,success:string){setBusy(true);setMessage('');try{await api<State>(path,payload);setData(await api<State>('state?week='+encodeURIComponent(week)));setEditing(null);setBlocked({});setMessage(success);if(view==='oncall')setOncall(await api<OnCall>('oncall?team='+encodeURIComponent(team)));}catch(e){setMessage((e as Error).message);if(path==='publish'&&e instanceof ApiError&&e.blocked_shifts.length){setBlocked(Object.fromEntries(e.blocked_shifts.map(x=>[x.id,x.reason])));setView('schedule');const affected=[...new Set(data?.shifts.filter(s=>e.blocked_shifts.some(b=>b.id===s.id)).map(s=>s.team)||[])];if(affected.length)setTeam(affected.length===1?affected[0]:'all');}}finally{setBusy(false);}}
 function openCoverage(c?:Coverage){setEditing('coverage');setForm(c?{...c,start:inputTime(c.start),end:inputTime(c.end),weight:Math.round(c.weight*100)}:{team:team==='all'?data?.teams[0]?.key:team,start:week+'T08:00',end:week+'T16:00',mode:'staffed',required:1,weight:80,skill:data?.teams.find(x=>x.key===team)?.skill||''});}
 function openShift(s?:Shift){setEditing('shift');setForm(s?{...s,start:inputTime(s.start),end:inputTime(s.end)}:{team:team==='all'?data?.teams[0]?.key:team,employee:'',start:week+'T08:00',end:week+'T16:00',mode:'staffed'});}
 function openPerson(p?:Person){setEditing('person');setForm(p?{...p,preferences:{...p.preferences},availability:[...p.availability],available_windows:[...(p.available_windows||[])]}:{key:'',name:'',phone:'',team:team==='all'?data?.teams[0]?.key:team,classification:'full_time',skills:[],preferences:{...defaultPreferences},availability:[],available_windows:[]});}
 function openTeam(t?:Team){setEditing('team');setForm(t?{...t,preferences:{...t.preferences},coverage_template:t.coverage_template.map(x=>({...x}))}:{key:'',name:'',skill:'',preferences:{...defaultPreferences},coverage_template:[]});}
 const set=(key:string,value:any)=>setForm(f=>({...f,[key]:value}));
 const save=()=>{try{if(editing==='coverage')act('coverage',{...form,start:toInstant(form.start),end:toInstant(form.end),weight:Number(form.weight)/100},'Coverage saved');if(editing==='shift')act('shift',{...form,start:toInstant(form.start),end:toInstant(form.end)},'Shift saved');if(editing==='person')act('person',{...form,week},'Person saved');if(editing==='team')act('team',{...form,week},'Team saved');}catch{setMessage('Enter valid start and end times.')}};
 const remove=()=>{if(!form.id||!confirm('Remove this draft item?'))return;act(editing!,{id:form.id,delete:true},'Removed');};
 const nav:[typeof view,string,React.ReactNode][]=[['schedule','Schedule',<CalendarDays size={18}/>],['coverage','Coverage',<Layers size={18}/>],['oncall','On-call',<PhoneCall size={18}/>],['people','People',<UsersRound size={18}/>],['teams','Teams',<Settings2 size={18}/>],['help','Help',<CircleHelp size={18}/>]];
 return <div className="app"><aside className="sidebar"><div className="brand"><span className="brand-mark"><CalendarDays size={22}/></span><span>Coverage<br/><strong>Scheduler</strong></span></div><div className="workspace">PILOT WORKSPACE<span>IT Operations</span></div><nav aria-label="Main navigation">{nav.map(([key,label,icon])=><button key={key} className={view===key?'active':''} onClick={()=>{setView(key);setEditing(null)}}>{icon}{label}</button>)}</nav><div className="side-bottom">Version 0.04 · synthetic data</div></aside><main><header className="topbar"><div><span className="eyebrow">PILOT / {view.toUpperCase()}</span><h1>{nav.find(x=>x[0]===view)?.[1]}</h1></div>{(view==='schedule'||view==='coverage'||view==='oncall')&&<span className="top-pill">{data?.batch==='draft'?'Draft':'Published'} · Pacific time</span>}</header>
 {message&&<div className="notice" role="status">{message}<button onClick={()=>setMessage('')}>×</button></div>}
 {view!=='help'&&<section className="toolbar"><div className="controls">{view!=='oncall'&&view!=='teams'&&<div className="week-control"><button className="quiet" aria-label="Previous week" onClick={()=>moveWeek(-1)}>‹</button><label>Week of<input type="date" value={week} onChange={e=>setWeek(e.target.value)}/></label><button className="quiet" aria-label="Next week" onClick={()=>moveWeek(1)}>›</button></div>}{view!=='teams'&&<label>Team<select value={team} onChange={e=>setTeam(e.target.value)}><option value="all">All teams · grouped</option>{data?.teams.map(t=><option key={t.key} value={t.key}>{t.name}</option>)}</select></label>}</div><div className="actions">{(view==='schedule'||view==='coverage')&&<><button className="secondary" disabled={busy} onClick={()=>act('generate',{week},'Draft ready for review')}><RefreshCw size={16}/> {data?.batch==='draft'?'Reset draft':'Create draft'}</button><button className="primary" disabled={busy||data?.batch!=='draft'} onClick={()=>act('publish',{week},'Schedule published')}><Send size={16}/> Publish</button></>}{view==='coverage'&&<button className="primary" disabled={data?.batch!=='draft'} onClick={()=>openCoverage()}><Plus size={16}/> Coverage period</button>}{view==='schedule'&&<button className="primary" disabled={data?.batch!=='draft'} onClick={()=>openShift()}><Plus size={16}/> Shift</button>}{view==='people'&&<button className="primary" onClick={()=>openPerson()}><Plus size={16}/> Person</button>}{view==='teams'&&<button className="primary" onClick={()=>openTeam()}><Plus size={16}/> Team</button>}</div></section>}
 {(view==='coverage'||view==='schedule')&&<><section className="summary"><div><span>Coverage periods</span><strong>{coverage.length}</strong><small>Demand windows</small></div><div><span>Fully covered</span><strong>{coverage.filter(c=>c.covered>=c.required).length}</strong><small>Entire interval covered</small></div><div><span>Coverage gaps</span><strong>{coverage.filter(c=>c.covered<c.required).length}</strong><small>Minimum headcount unmet</small></div><div><span>Employee shifts</span><strong>{shifts.length}</strong><small>Independent assignments</small></div></section>{data?.advisories.length?<section className="rule-advisories"><details><summary>BC scheduling review · {data.advisories.length} advisories</summary><ul>{data.advisories.map((n,i)=><li key={i}>{n.message}</li>)}</ul></details></section>:null}</>}
 {view==='coverage'&&<section className="roster"><div className="section-head"><div><h2>Coverage requirements</h2><p>Required time, headcount and skill. Edit a dated period here; edit recurring patterns under Teams.</p></div></div><div className="days">{days.map(day=><div className="day" key={day}><h3>{day}</h3>{coverage.filter(c=>dateKey(c.start)===day).map(c=><article className={'slot '+(c.covered<c.required?'slot-gap':'slot-covered')} key={c.id}><div className="slot-top"><span>{team==='all'&&teamName(c.team)+' · '}{c.mode==='on_call'?'On-call':'Staffed'}</span><b>{c.covered}/{c.required}</b></div><div className="slot-time">{inputTime(c.start).slice(11)}–{inputTime(c.end).slice(11)} <span>{Math.round(c.weight*100)}%</span></div><small>{c.skill} · {c.covered_minutes}/{c.total_minutes} min at target</small>{data?.batch==='draft'&&<button className="edit-link" onClick={()=>openCoverage(c)}>Edit period</button>}</article>)}</div>)}</div></section>}
 {view==='schedule'&&<><ScheduleRecords week={week} team={team} weeks={data?.published_weeks||[]} revisions={data?.revisions.length||0} absences={data?.absences||[]} callouts={data?.callouts||[]} people={data?.employees||[]} onWeek={setWeek} onAction={act} displayTime={displayTime} toInstant={toInstant}/><section className="lookup"><div className="lookup-icon"><Layers size={20}/></div><div className="lookup-copy"><h2>Assignments are independent of Coverage</h2><p>A person's start and end times can span several coverage periods. Coverage counts recalculate from overlapping qualified shifts.</p></div></section><section className="roster"><div className="section-head"><div><h2>Employee schedule</h2><p>Who works, when, and for how long. {data?.batch==='published'?'Create a draft to edit published shifts.':''}</p></div></div><div className="days">{days.map(day=><div className="day" key={day}><h3>{day}</h3>{shifts.filter(s=>dateKey(s.start)===day).map(s=><article className={'slot '+(blocked[s.id]?'slot-blocked':'')} key={s.id} aria-label={blocked[s.id]?'Publish blocked: '+blocked[s.id]:undefined}><div className="slot-top"><span>{team==='all'&&teamName(s.team)+' · '}{s.mode==='on_call'?'On-call':'Staffed'}</span><b>{s.cross_team?'↗':''}</b></div><div className="slot-time">{inputTime(s.start).slice(11)}–{inputTime(s.end).slice(11)}</div><div className="slot-people">{people.get(s.employee)?.name||s.employee}</div>{(s.role||s.location||s.break_minutes>0)&&<small>{[s.role,s.location,s.break_minutes>0?`${s.break_minutes} min break`:''].filter(Boolean).join(' · ')}</small>}{s.notes&&<small>{s.notes}</small>}{data?.batch==='published'&&s.mode==='on_call'&&<button className="edit-link" onClick={()=>{setCalloutShift(s);setCalloutStart(inputTime(s.start));setCalloutEnd(inputTime(s.end));setCalloutNote('')}}>Record call-out</button>}{blocked[s.id]&&<div className="block-reason" role="alert"><strong>Publish blocked</strong><span>{blocked[s.id]}</span></div>}{data?.batch==='draft'&&<button className="edit-link" onClick={()=>openShift(s)}>Edit shift</button>}</article>)}</div>)}</div></section></>}
 {view==='oncall'&&<section className="people-view"><div className="section-head"><div><h2>{labels.onCallHeading}</h2><p>Published staffed and standby assignments · current and next eight · contact information from People.</p></div><button className="quiet" onClick={()=>api<OnCall>('oncall?team='+encodeURIComponent(team)).then(setOncall)}>Refresh</button></div><div className="oncall-list">{oncall?.people.length?oncall.people.map((p,i)=><article key={p.id} className="oncall-card"><div className="oncall-card-top"><span className="eyebrow">{p.current?labels.current:labels.upcoming} · {teamName(p.team)}</span><span className="oncall-mode">{p.mode==='staffed'?labels.staffed:labels.standby}</span></div><h3>{p.name}</h3>{p.phone?<a href={'tel:'+p.phone}>{p.phone}</a>:<strong className="missing-contact">{labels.missingPhone}</strong>}<p>{displayTime(p.start)} → {displayTime(p.end)}</p>{p.current&&oncall.people[i+1]&&<small>Next: {oncall.people[i+1].name} · {displayTime(oncall.people[i+1].start)}</small>}</article>):<p>No current or upcoming published assignments for this team.</p>}{oncall?.gaps.map((g,i)=><article key={i} className="oncall-card gap"><strong>Coverage gap · {teamName(g.team)}</strong><p>{displayTime(g.start)} → {displayTime(g.end)} · {g.missing} missing</p></article>)}</div></section>}
 {view==='people'&&<section className="people-view"><div className="section-head"><div><h2>People & preferences</h2><p>Contact details, qualifications, availability and individual shift preferences.</p></div><label className="directory-search">Search people<input type="search" value={peopleSearch} onChange={e=>setPeopleSearch(e.target.value)} placeholder="Name, team, or skill"/></label></div>{data?.teams.filter(t=>(team==='all'||t.key===team)&&data.employees.some(p=>p.team===t.key&&personMatches(p))).map(t=><div className="people-group" key={t.key}><h3>{t.name}</h3><div className="person-grid">{data.employees.filter(p=>p.team===t.key&&personMatches(p)).map(p=><button className="person person-button" key={p.key} onClick={()=>openPerson(p)}><span className="person-avatar">{p.name.split(' ').map(x=>x[0]).join('')}</span><span><strong>{p.name}</strong><small>{p.classification.replace('_',' ')} · {p.phone}</small><small>{p.skills.join(', ')}</small></span></button>)}</div></div>)}{data&&data.employees.filter(p=>(team==='all'||p.team===team)&&personMatches(p)).length===0&&<p className="directory-empty">No people match this search in the selected team.</p>}</section>}
 {view==='teams'&&<section className="people-view"><div className="section-head"><div><h2>Teams</h2><p>Manage team defaults and recurring coverage. Select a team to edit its details.</p></div><label className="directory-search">Search teams<input type="search" value={teamSearch} onChange={e=>setTeamSearch(e.target.value)} placeholder="Team name"/></label></div><div className="team-directory">{matchingTeams.map(t=><button className="team-directory-row" key={t.key} onClick={()=>openTeam(t)}><span className="person-avatar">{t.name[0]}</span><span className="team-directory-copy"><strong>{t.name}</strong><small>{t.skill} · {data?.employees.filter(p=>p.team===t.key).length||0} people · {t.coverage_template.length} recurring periods</small></span><span className="team-edit">Edit →</span></button>)}{!matchingTeams.length&&<p className="directory-empty">No teams match this search.</p>}</div></section>}
 {view==='help'&&<section className="help-view"><div className="section-head"><h2>How this pilot works</h2></div><div className="help-grid"><article><h3>Coverage</h3><p>Required periods, headcount, skills and relative priority. These are demands, not employee shifts. Team templates create new weeks; dated periods can be edited in a draft.</p></article><article><h3>Schedule</h3><p>Independent employee shifts may span multiple coverage periods. Draft and publish are separate; the on-call contact view reads published shifts only.</p></article><article><h3>Preferences</h3><p>Team defaults and individual preferences guide candidate ranking. Qualifications, availability, overlap and worked-shift rest remain eligibility checks.</p></article><article><h3>BC review</h3><p>Home/mobile standby is assumed. Actual call-outs, payroll, agreements, exceptions and adjacent-week rest must be reviewed separately before operational use.</p></article></div><p className="help-foot"><a href="/project-requirements.xml" target="_blank" rel="noreferrer">Full requirements</a></p></section>}
 {calloutShift&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setCalloutShift(null)}}><section className="modal" role="dialog" aria-modal="true" aria-label="Record standby call-out"><div className="modal-head"><h2>Record actual standby work</h2><button onClick={()=>setCalloutShift(null)} aria-label="Close">×</button></div><p>{people.get(calloutShift.employee)?.name} · {displayTime(calloutShift.start)} → {displayTime(calloutShift.end)}</p><div className="form-grid"><label>Start · Pacific<input type="datetime-local" value={calloutStart} onChange={e=>setCalloutStart(e.target.value)}/></label><label>End · Pacific<input type="datetime-local" value={calloutEnd} onChange={e=>setCalloutEnd(e.target.value)}/></label><label>Note<input value={calloutNote} onChange={e=>setCalloutNote(e.target.value)}/></label></div><div className="modal-actions"><button className="quiet" onClick={()=>setCalloutShift(null)}>Cancel</button><button className="primary" onClick={()=>{try{act('callout',{shift:calloutShift.id,start:toInstant(calloutStart),end:toInstant(calloutEnd),note:calloutNote},'Call-out recorded');setCalloutShift(null)}catch{setMessage('Enter valid call-out times.')}}}>Save</button></div></section></div>}
 {editing&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><section className="modal" role="dialog" aria-modal="true" aria-label={'Edit '+editing}><div className="modal-head"><h2>{form.id?'Edit':'Add'} {editing==='shift'?'shift':editing==='coverage'?'coverage period':editing}</h2><button onClick={()=>setEditing(null)} aria-label="Close">×</button></div>
 {(editing==='coverage'||editing==='shift')&&<div className="form-grid"><label>Team<select value={form.team||''} onChange={e=>set('team',e.target.value)}>{data?.teams.map(t=><option key={t.key} value={t.key}>{t.name}</option>)}</select></label>{editing==='shift'?<label>Person<select value={form.employee||''} onChange={e=>set('employee',e.target.value)}><option value="">Select person</option>{data?.employees.filter(p=>p.skills.includes(data.teams.find(t=>t.key===form.team)?.skill||'')).map(p=><option key={p.key} value={p.key}>{p.name} · {teamName(p.team)}</option>)}</select></label>:<label>Required skill<input value={form.skill||''} onChange={e=>set('skill',e.target.value)}/></label>}<label>Start · Pacific<input type="datetime-local" value={form.start||''} onChange={e=>set('start',e.target.value)}/></label><label>End · Pacific<input type="datetime-local" value={form.end||''} onChange={e=>set('end',e.target.value)}/></label><label>Mode<select value={form.mode||'staffed'} onChange={e=>set('mode',e.target.value)}><option value="staffed">Staffed</option><option value="on_call">On-call</option></select></label>{editing==='shift'&&<><label>Role<input value={form.role||''} onChange={e=>set('role',e.target.value)}/></label><label>Work location<input value={form.location||''} onChange={e=>set('location',e.target.value)}/></label><label>Break minutes · informational<input type="number" min="0" value={form.break_minutes||0} onChange={e=>set('break_minutes',Number(e.target.value))}/></label><label>Notes<input value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></label></>}{editing==='coverage'&&<><label>Required people<input type="number" min="0" max="20" value={form.required} onChange={e=>set('required',+e.target.value)}/></label><label>Importance %<input type="number" min="1" max="100" value={form.weight} onChange={e=>set('weight',+e.target.value)}/></label></>}</div>}
 {editing==='person'&&<><div className="form-grid"><label>ID<input value={form.key||''} disabled={!!data?.employees.find(p=>p.key===form.key)} onChange={e=>set('key',e.target.value)}/></label><label>Name<input value={form.name||''} onChange={e=>set('name',e.target.value)}/></label><label>Phone<input type="tel" value={form.phone||''} onChange={e=>set('phone',e.target.value)}/></label><label>Home team<select value={form.team||''} onChange={e=>set('team',e.target.value)}>{data?.teams.map(t=><option value={t.key} key={t.key}>{t.name}</option>)}</select></label><label>Classification<select value={form.classification||'casual'} onChange={e=>set('classification',e.target.value)}><option value="full_time">Full-time</option><option value="casual">Casual</option><option value="part_time">Part-time</option></select></label><label>Skills · comma separated<input value={(form.skills||[]).join(', ')} onChange={e=>set('skills',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label></div><h3>Individual preferences</h3><PrefFields value={form.preferences||{}} onChange={p=>set('preferences',p)}/><AvailabilityCalendar name={form.name||''} casual={form.classification==='casual'} available={form.available_windows||[]} unavailable={form.availability||[]} onAvailable={v=>set('available_windows',v)} onUnavailable={v=>set('availability',v)} initialDay={week} dateKey={dateKey} inputTime={inputTime} toInstant={toInstant}/></>}
 {editing==='team'&&<><div className="form-grid"><label>Team ID<input value={form.key||''} disabled={!!data?.teams.find(t=>t.key===form.key)} onChange={e=>set('key',e.target.value)}/></label><label>Name<input value={form.name||''} onChange={e=>set('name',e.target.value)}/></label><label>Default required skill<input value={form.skill||''} onChange={e=>set('skill',e.target.value)}/></label></div><h3>Team preferences</h3><PrefFields value={form.preferences||{}} onChange={p=>set('preferences',p)}/><h3>Repeating weekly Coverage template</h3><p className="form-hint">Days: 0 Monday through 6 Sunday. Times: 0–24 local hours. New weeks use this template.</p>{(form.coverage_template||[]).map((r:Template,i:number)=><div className="template-row" key={i}><label>Days<input value={r.days.join(',')} onChange={e=>{const v=[...form.coverage_template];v[i]={...r,days:e.target.value.split(',').map(Number)};set('coverage_template',v)}}/></label><label>Start<input type="number" min="0" max="23" value={r.start} onChange={e=>{const v=[...form.coverage_template];v[i]={...r,start:+e.target.value};set('coverage_template',v)}}/></label><label>End<input type="number" min="1" max="24" value={r.end} onChange={e=>{const v=[...form.coverage_template];v[i]={...r,end:+e.target.value};set('coverage_template',v)}}/></label><label>Mode<select value={r.mode} onChange={e=>{const v=[...form.coverage_template];v[i]={...r,mode:e.target.value};set('coverage_template',v)}}><option value="staffed">Staffed</option><option value="on_call">On-call</option></select></label><label>People<input type="number" min="0" max="20" value={r.required} onChange={e=>{const v=[...form.coverage_template];v[i]={...r,required:+e.target.value};set('coverage_template',v)}}/></label><label>Weight<input type="number" min=".01" max="1" step=".01" value={r.weight} onChange={e=>{const v=[...form.coverage_template];v[i]={...r,weight:+e.target.value};set('coverage_template',v)}}/></label><button className="quiet" onClick={()=>set('coverage_template',form.coverage_template.filter((_:unknown,j:number)=>j!==i))}>Remove</button></div>)}<button className="quiet" onClick={()=>set('coverage_template',[...(form.coverage_template||[]),{days:[0,1,2,3,4],start:8,end:16,mode:'staffed',required:1,weight:.8}])}>Add repeating period</button></>}
 <div className="modal-actions">{form.id&&<button className="danger" onClick={remove}>Delete draft item</button>}<button className="quiet" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={busy} onClick={save}>Save</button></div></section></div>}
 </main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
