# Generated by Django 5.2.17 on 2026-09-23 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageslot',
            name='required_skill',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='availability',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='team',
            name='coverage_template',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='team',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('mode', models.CharField(max_length=20)),
                ('batch', models.CharField(default='draft', max_length=20)),
                ('published', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.team')),
            ],
        ),
    ]
