# Generated by Django 5.2.17 on 2026-09-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coverageslot_required_skill_employee_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='available_windows',
            field=models.JSONField(default=list),
        ),
    ]
