# Generated by Django 5.2.17 on 2026-09-23 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_available_windows'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(default='Alpha administrator', max_length=80)),
                ('action', models.CharField(max_length=60)),
                ('week', models.DateField(blank=True, null=True)),
                ('detail', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shift',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='shift',
            name='role',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('kind', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Callout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standby_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(db_index=True)),
                ('revision', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(default='Alpha administrator', max_length=80)),
                ('snapshot', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-week', '-revision'],
                'constraints': [models.UniqueConstraint(fields=('week', 'revision'), name='unique_week_revision')],
            },
        ),
    ]
