# Generated by Django 5.2.17 on 2026-09-23 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scheduleevent_shift_break_minutes_shift_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callout',
            name='employee_key',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='callout',
            name='employee_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='callout',
            name='team_key',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='callout',
            name='standby_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shift'),
        ),
    ]
